name: release

on:
  push:
    tags:
      - 'v*'     # e.g., v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed to create the release & upload assets

    env:
      GOOS: linux
      GOARCH: arm64         # or amd64; must match your Lambda architecture
      CGO_ENABLED: 0
      TAG: ${{ github.ref_name }}                  # e.g., v1.0.0
      ASSET_NAME: function-${{ github.ref_name }}.zip

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build bootstrap (deterministic)
        run: |
          go build -tags lambda.norpc -trimpath -ldflags "-s -w -buildid=" -o bootstrap ./cmd/lambda

      - name: Zip with fixed perms/time (Go zipper)
        run: |
          go run ./tools/zipper bootstrap
          mv function.zip "$ASSET_NAME"
          ls -l "$ASSET_NAME"

      - name: Create GitHub Release & upload asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: ${{ env.TAG }}
          draft: false
          prerelease: false
          files: |
            ${{ env.ASSET_NAME }}
